#!/usr/bin/env python3
"""Rebake the LeKiwi browser mesh from one reviewed immutable checkout.

The historical mesh baker is intentionally accepted as an explicit input so
its exact bytes can be reviewed and hash-locked without silently vendoring an
unreviewed tool. The output records both source and generator provenance.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import subprocess
import tempfile
from pathlib import Path

PINNED_REVISION = "efa608d7ee5a495a4803b1d28cd0c955b4f1e033"
PINNED_URDF_SHA256 = "47887649403f212ee2853850a01affe1e36aff454aa1998d5265ac4ac2d5a49d"
REVIEWED_GENERATOR_SHA256 = "c73beda849c84f579163c59c7b892c881f1496316d87cf67745fdda13459a69b"
SOURCE_URL = f"https://github.com/SIGRobotics-UIUC/LeKiwi/blob/{PINNED_REVISION}/URDF/LeKiwi.urdf"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", required=True, type=Path, help="LeKiwi Git checkout at the pinned commit")
    parser.add_argument("--generator", required=True, type=Path, help="Reviewed build-robot-rig-mesh-data.py")
    parser.add_argument("--out", required=True, type=Path, help="Destination simulator/js directory")
    args = parser.parse_args()

    source_root = args.source_root.resolve()
    generator = args.generator.resolve()
    urdf = source_root / "URDF" / "LeKiwi.urdf"
    revision = subprocess.check_output(["git", "-C", str(source_root), "rev-parse", "HEAD"], text=True).strip()
    if revision != PINNED_REVISION:
        raise SystemExit(f"LeKiwi source revision mismatch: expected {PINNED_REVISION}, got {revision}")
    if sha256(urdf) != PINNED_URDF_SHA256:
        raise SystemExit("Pinned LeKiwi URDF SHA-256 mismatch")
    if sha256(generator) != REVIEWED_GENERATOR_SHA256:
        raise SystemExit("Reviewed mesh generator SHA-256 mismatch")

    spec = importlib.util.spec_from_file_location("robobuddy_reviewed_mesh_baker", generator)
    if spec is None or spec.loader is None:
        raise SystemExit("Unable to load reviewed mesh generator")
    baker = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(baker)

    recipe = dict(baker.ROBOTS["lekiwi"])
    recipe["urdf_url"] = urdf.as_uri()
    recipe["mesh_base_url"] = (source_root / "URDF").as_uri().rstrip("/") + "/"
    # The reviewed immutable URDF uses the current normalized arm joint names;
    # the historical baker recipe named the older CAD-export joints.
    recipe["joint_map"] = {
        "arm_shoulder_pan": "shoulder_pan",
        "arm_shoulder_lift": "shoulder_lift",
        "arm_elbow_flex": "elbow_flex",
        "arm_wrist_flex": "wrist_flex",
        "arm_wrist_roll": "wrist_roll",
    }
    recipe["gripper_joint"] = "arm_gripper"
    args.out.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="robobuddy-lekiwi-bake-") as cache:
        baker.CACHE_DIR = Path(cache)
        baker.bake_robot("lekiwi", recipe, args.out, offline=False)

    output = args.out / recipe["out_file"]
    prefix = "// Generated by tools/build-robot-rig-mesh-data.py. Do not edit.\nexport const ROBOT_RIG_MESH_DATA = Object.freeze("
    text = output.read_text(encoding="utf-8")
    if not text.startswith(prefix) or not text.endswith(");\n"):
        raise SystemExit("Unexpected generated module envelope")
    payload = json.loads(text[len(prefix) : -3])
    payload["source"] = {
        "urdf": SOURCE_URL,
        "revision": PINNED_REVISION,
        "urdfSha256": PINNED_URDF_SHA256,
        "license": "Apache-2.0",
        "generator": "tools/build-robot-rig-mesh-data.py",
        "generatorSha256": REVIEWED_GENERATOR_SHA256,
        "reproductionWrapper": "scripts/rebake-lekiwi-pinned.py",
        "geometryFrame": "three-y-up-meters",
        "transformFrame": "three-y-up-millimeters",
    }
    output.write_text(prefix + json.dumps(payload, separators=(",", ":")) + ");\n", encoding="utf-8")
    print(json.dumps({"output": str(output), "outputSha256": sha256(output), "sourceRevision": revision}, indent=2))


if __name__ == "__main__":
    main()
